services:
  postgres:
    volumes:
      - ${STREAMFORGE_POSTGRES_HOST_PATH:-./docker-data/postgres}:/var/lib/postgresql/data

  api:
    volumes:
      - ${STREAMFORGE_SHARED_DATA_HOST_PATH:-./docker-data/shared-data}:/app/data
      - ${STREAMFORGE_DATA_PROTECTION_KEYS_HOST_PATH:-./docker-data/data-protection-keys}:/app/data/keys
