// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StreamForge.Infrastructure.Data;

#nullable disable

namespace StreamForge.Infrastructure.Migrations
{
    [DbContext(typeof(StreamForgeDbContext))]
    [Migration("20260621142035_AddTranscriptChunksAndSystemSettings")]
    partial class AddTranscriptChunksAndSystemSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StreamForge.Domain.Entities.AccessControl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PermissionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShareToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShareToken")
                        .IsUnique()
                        .HasDatabaseName("IX_AccessControls_ShareToken")
                        .HasFilter("\"ShareToken\" IS NOT NULL");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AccessControls_UserId");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("IX_AccessControls_VideoId");

                    b.HasIndex("VideoId", "UserId")
                        .HasDatabaseName("IX_AccessControls_VideoId_UserId");

                    b.ToTable("AccessControls", (string)null);
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.AnalyticsEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationWatched")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<int?>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AnalyticsEvents_CreatedAt");

                    b.HasIndex("EventType")
                        .HasDatabaseName("IX_AnalyticsEvents_EventType");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_AnalyticsEvents_SessionId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AnalyticsEvents_UserId");

                    b.HasIndex("UserId1");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("IX_AnalyticsEvents_VideoId");

                    b.HasIndex("VideoId", "EventTime")
                        .HasDatabaseName("IX_AnalyticsEvents_VideoId_EventTime");

                    b.ToTable("AnalyticsEvents", (string)null);
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.Bookmark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("TimestampSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Bookmarks_UserId");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("IX_Bookmarks_VideoId");

                    b.HasIndex("UserId", "VideoId")
                        .HasDatabaseName("IX_Bookmarks_UserId_VideoId");

                    b.HasIndex("UserId", "VideoId", "TimestampSeconds")
                        .HasDatabaseName("IX_Bookmarks_UserId_VideoId_TimestampSeconds");

                    b.ToTable("Bookmarks", (string)null);
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Categories_Name");

                    b.HasIndex("ParentCategoryId")
                        .HasDatabaseName("IX_Categories_ParentCategoryId");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VideoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Notifications_CreatedAt");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Notifications_UserId");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("IX_Notifications_VideoId");

                    b.HasIndex("UserId", "IsRead")
                        .HasDatabaseName("IX_Notifications_UserId_IsRead");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VideoCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Playlists_CreatedAt");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("IX_Playlists_OwnerId");

                    b.HasIndex("Visibility")
                        .HasDatabaseName("IX_Playlists_Visibility");

                    b.ToTable("Playlists", (string)null);
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.PlaylistVideo", b =>
                {
                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("PlaylistId", "VideoId");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("IX_PlaylistVideos_VideoId");

                    b.HasIndex("PlaylistId", "OrderIndex")
                        .HasDatabaseName("IX_PlaylistVideos_PlaylistId_OrderIndex");

                    b.HasIndex("PlaylistId", "VideoId")
                        .IsUnique()
                        .HasDatabaseName("IX_PlaylistVideos_PlaylistId_VideoId");

                    b.ToTable("PlaylistVideos", (string)null);
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.StorageProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_StorageProviders_IsActive");

                    b.HasIndex("IsDefault")
                        .HasDatabaseName("IX_StorageProviders_IsDefault");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_StorageProviders_Type");

                    b.ToTable("StorageProviders", (string)null);
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("IX_SystemSettings_Key");

                    b.ToTable("SystemSettings", (string)null);
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Tags_Name");

                    b.HasIndex("UsageCount")
                        .HasDatabaseName("IX_Tags_UsageCount");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.UploadSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StorageProviderType")
                        .HasColumnType("integer");

                    b.Property<string>("TemporaryStoragePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<long>("TotalSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UploadedSize")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_UploadSessions_ExpiresAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_UploadSessions_Status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UploadSessions_UserId");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("IX_UploadSessions_VideoId");

                    b.ToTable("UploadSessions", (string)null);
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.UploadSessionPart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<int>("PartNumber")
                        .HasColumnType("integer");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("UploadSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsComplete")
                        .HasDatabaseName("IX_UploadSessionParts_IsComplete");

                    b.HasIndex("UploadSessionId")
                        .HasDatabaseName("IX_UploadSessionParts_UploadSessionId");

                    b.HasIndex("UploadSessionId", "PartNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_UploadSessionParts_SessionId_PartNumber");

                    b.ToTable("UploadSessionParts", (string)null);
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("Role")
                        .HasDatabaseName("IX_Users_Role");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowComments")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("AllowLikes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("Autoplay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("CaptionsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DefaultVolume")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("Loop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PlayerTheme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("default");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Ready");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploaderId")
                        .HasColumnType("uuid");

                    b.Property<long>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Videos_CategoryId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Videos_CreatedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Videos_Status");

                    b.HasIndex("UploaderId")
                        .HasDatabaseName("IX_Videos_UploaderId");

                    b.HasIndex("ViewCount")
                        .HasDatabaseName("IX_Videos_ViewCount");

                    b.HasIndex("Visibility")
                        .HasDatabaseName("IX_Videos_Visibility");

                    b.ToTable("Videos", (string)null);
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.VideoComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEdited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_VideoComments_CreatedAt");

                    b.HasIndex("ParentCommentId")
                        .HasDatabaseName("IX_VideoComments_ParentCommentId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_VideoComments_UserId");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("IX_VideoComments_VideoId");

                    b.ToTable("VideoComments", (string)null);
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.VideoFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Checksum")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("StorageProviderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VideoVersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Checksum")
                        .HasDatabaseName("IX_VideoFiles_Checksum");

                    b.HasIndex("FilePath")
                        .HasDatabaseName("IX_VideoFiles_FilePath");

                    b.HasIndex("StorageProviderId")
                        .HasDatabaseName("IX_VideoFiles_StorageProviderId");

                    b.HasIndex("VideoVersionId")
                        .HasDatabaseName("IX_VideoFiles_VideoVersionId");

                    b.ToTable("VideoFiles", (string)null);
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.VideoProcessingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_VideoProcessingJobs_Status");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("IX_VideoProcessingJobs_VideoId");

                    b.HasIndex("VideoId", "JobType")
                        .HasDatabaseName("IX_VideoProcessingJobs_VideoId_JobType");

                    b.ToTable("VideoProcessingJobs", (string)null);
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.VideoReaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_VideoReactions_UserId");

                    b.HasIndex("VideoId", "ReactionType")
                        .HasDatabaseName("IX_VideoReactions_VideoId_ReactionType");

                    b.HasIndex("VideoId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_VideoReactions_VideoId_UserId");

                    b.ToTable("VideoReactions", (string)null);
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.VideoTag", b =>
                {
                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("VideoId", "TagId");

                    b.HasIndex("TagId")
                        .HasDatabaseName("IX_VideoTags_TagId");

                    b.ToTable("VideoTags", (string)null);
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.VideoThumbnail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("TimestampSeconds")
                        .HasColumnType("integer");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("IX_VideoThumbnails_VideoId");

                    b.HasIndex("VideoId", "IsDefault")
                        .HasDatabaseName("IX_VideoThumbnails_VideoId_IsDefault");

                    b.ToTable("VideoThumbnails", (string)null);
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.VideoTranscriptChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("EndSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<double>("StartSeconds")
                        .HasColumnType("double precision");

                    b.Property<Guid>("TranscriptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TranscriptionId")
                        .HasDatabaseName("IX_VideoTranscriptChunks_TranscriptionId");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("IX_VideoTranscriptChunks_VideoId");

                    b.HasIndex("VideoId", "Language")
                        .HasDatabaseName("IX_VideoTranscriptChunks_VideoId_Language");

                    b.HasIndex("VideoId", "StartSeconds")
                        .HasDatabaseName("IX_VideoTranscriptChunks_VideoId_StartSeconds");

                    b.ToTable("VideoTranscriptChunks", (string)null);
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.VideoTranscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkerJobId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_VideoTranscriptions_CorrelationId");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("IX_VideoTranscriptions_VideoId");

                    b.HasIndex("WorkerJobId")
                        .HasDatabaseName("IX_VideoTranscriptions_WorkerJobId");

                    b.HasIndex("VideoId", "Language", "Format")
                        .IsUnique()
                        .HasDatabaseName("IX_VideoTranscriptions_VideoId_Language_Format");

                    b.ToTable("VideoTranscriptions", (string)null);
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.VideoVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Bitrate")
                        .HasColumnType("integer");

                    b.Property<string>("Codec")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Resolution")
                        .HasDatabaseName("IX_VideoVersions_Resolution");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("IX_VideoVersions_VideoId");

                    b.ToTable("VideoVersions", (string)null);
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.AccessControl", b =>
                {
                    b.HasOne("StreamForge.Domain.Entities.User", "User")
                        .WithMany("AccessControls")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StreamForge.Domain.Entities.Video", "Video")
                        .WithMany("AccessControls")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.AnalyticsEvent", b =>
                {
                    b.HasOne("StreamForge.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StreamForge.Domain.Entities.User", null)
                        .WithMany("AnalyticsEvents")
                        .HasForeignKey("UserId1");

                    b.HasOne("StreamForge.Domain.Entities.Video", "Video")
                        .WithMany("AnalyticsEvents")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.Bookmark", b =>
                {
                    b.HasOne("StreamForge.Domain.Entities.User", "User")
                        .WithMany("Bookmarks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StreamForge.Domain.Entities.Video", "Video")
                        .WithMany("Bookmarks")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.Category", b =>
                {
                    b.HasOne("StreamForge.Domain.Entities.Category", "ParentCategory")
                        .WithMany("Subcategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.Notification", b =>
                {
                    b.HasOne("StreamForge.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StreamForge.Domain.Entities.Video", "Video")
                        .WithMany("Notifications")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.Playlist", b =>
                {
                    b.HasOne("StreamForge.Domain.Entities.User", "Owner")
                        .WithMany("Playlists")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.PlaylistVideo", b =>
                {
                    b.HasOne("StreamForge.Domain.Entities.Playlist", "Playlist")
                        .WithMany("PlaylistVideos")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StreamForge.Domain.Entities.Video", "Video")
                        .WithMany("PlaylistVideos")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.UploadSession", b =>
                {
                    b.HasOne("StreamForge.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StreamForge.Domain.Entities.Video", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.UploadSessionPart", b =>
                {
                    b.HasOne("StreamForge.Domain.Entities.UploadSession", null)
                        .WithMany()
                        .HasForeignKey("UploadSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.Video", b =>
                {
                    b.HasOne("StreamForge.Domain.Entities.Category", "Category")
                        .WithMany("Videos")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StreamForge.Domain.Entities.User", "Uploader")
                        .WithMany("Videos")
                        .HasForeignKey("UploaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.VideoComment", b =>
                {
                    b.HasOne("StreamForge.Domain.Entities.VideoComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StreamForge.Domain.Entities.User", "User")
                        .WithMany("VideoComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StreamForge.Domain.Entities.Video", "Video")
                        .WithMany("VideoComments")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentComment");

                    b.Navigation("User");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.VideoFile", b =>
                {
                    b.HasOne("StreamForge.Domain.Entities.StorageProvider", "StorageProvider")
                        .WithMany("VideoFiles")
                        .HasForeignKey("StorageProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StreamForge.Domain.Entities.VideoVersion", "VideoVersion")
                        .WithMany("Files")
                        .HasForeignKey("VideoVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StorageProvider");

                    b.Navigation("VideoVersion");
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.VideoProcessingJob", b =>
                {
                    b.HasOne("StreamForge.Domain.Entities.Video", "Video")
                        .WithMany("VideoProcessingJobs")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.VideoReaction", b =>
                {
                    b.HasOne("StreamForge.Domain.Entities.User", "User")
                        .WithMany("VideoReactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StreamForge.Domain.Entities.Video", "Video")
                        .WithMany("VideoReactions")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.VideoTag", b =>
                {
                    b.HasOne("StreamForge.Domain.Entities.Tag", "Tag")
                        .WithMany("VideoTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StreamForge.Domain.Entities.Video", "Video")
                        .WithMany("VideoTags")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.VideoThumbnail", b =>
                {
                    b.HasOne("StreamForge.Domain.Entities.Video", "Video")
                        .WithMany("VideoThumbnails")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.VideoTranscriptChunk", b =>
                {
                    b.HasOne("StreamForge.Domain.Entities.VideoTranscription", "Transcription")
                        .WithMany("TranscriptChunks")
                        .HasForeignKey("TranscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StreamForge.Domain.Entities.Video", "Video")
                        .WithMany("VideoTranscriptChunks")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transcription");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.VideoTranscription", b =>
                {
                    b.HasOne("StreamForge.Domain.Entities.Video", "Video")
                        .WithMany("VideoTranscriptions")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.VideoVersion", b =>
                {
                    b.HasOne("StreamForge.Domain.Entities.Video", "Video")
                        .WithMany("VideoVersions")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.Category", b =>
                {
                    b.Navigation("Subcategories");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.Playlist", b =>
                {
                    b.Navigation("PlaylistVideos");
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.StorageProvider", b =>
                {
                    b.Navigation("VideoFiles");
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.Tag", b =>
                {
                    b.Navigation("VideoTags");
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.User", b =>
                {
                    b.Navigation("AccessControls");

                    b.Navigation("AnalyticsEvents");

                    b.Navigation("Bookmarks");

                    b.Navigation("Notifications");

                    b.Navigation("Playlists");

                    b.Navigation("VideoComments");

                    b.Navigation("VideoReactions");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.Video", b =>
                {
                    b.Navigation("AccessControls");

                    b.Navigation("AnalyticsEvents");

                    b.Navigation("Bookmarks");

                    b.Navigation("Notifications");

                    b.Navigation("PlaylistVideos");

                    b.Navigation("VideoComments");

                    b.Navigation("VideoProcessingJobs");

                    b.Navigation("VideoReactions");

                    b.Navigation("VideoTags");

                    b.Navigation("VideoThumbnails");

                    b.Navigation("VideoTranscriptChunks");

                    b.Navigation("VideoTranscriptions");

                    b.Navigation("VideoVersions");
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.VideoComment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.VideoTranscription", b =>
                {
                    b.Navigation("TranscriptChunks");
                });

            modelBuilder.Entity("StreamForge.Domain.Entities.VideoVersion", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
